export { Shape, isMatch, validate, expectMatch, ShapeMismatchError } from './core';
export { record, partial, structure } from './object';
export { array } from './array';
export { string, number, boolean } from './primitive';
export { union } from './union';
export { literal } from './literal';
export { tuple } from './tuple';
export { objectMap } from './objectMap';
export { constrained } from './constraint';
export { nullValue, undefinedValue, nullable, nullish, optional } from './optional';
export { intersection } from './intersection';
