export { Shape, isMatch, validate, expectMatch, ShapeMismatchError } from './lib/core';
export { record, partial, structure } from './lib/object';
export { array } from './lib/array';
export { string, number, boolean } from './lib/primitive';
export { union } from './lib/union';
export { literal } from './lib/literal';
export { tuple } from './lib/tuple';
export { dictionary } from './lib/dictionary';
export { constrained } from './lib/constraint';
export { nullLiteral, undefinedLiteral, nullable, nullish, optional } from './lib/optional';
export { intersection } from './lib/intersection';
